server:
  port: 8081

spring:
  application:
    name: xq-svc-testplan

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/xq_testplan_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:xq_user}
    password: ${DB_PASSWORD:xq_password}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

management:
  metrics:
    enable:
      system.cpu: false
      process.cpu: false
      jvm.processor: false